
<!-- Dump generated by dump.php layout -->

<h3>Global view data</h3>
<? var_dump(\Nerd\Design\Architectural\MVC\View::$global_data) ?>

<h3>Local view data</h3>
<?
	if (empty($this->data)) :
		echo '<pre>No data has been assigned to this view instance.</pre>';
	else :
		var_dump($this->data);
	endif
?>

<? if (isset($extras)) : ?>
<h3>Extra data</h3>
<? var_dump($extras) ?>
<? endif ?>